"""Shared dimensions for the full-screen Flet interface."""

PAGE_PADDING = 16
PANE_PADDING = 12
PANE_SPACING = 12
PANEL_PADDING = 16
PANEL_SPACING = 12
PANEL_BORDER_RADIUS = 8
PANEL_BORDER_WIDTH = 1

BUTTON_WIDTH = 160
BUTTON_HEIGHT = 42

LEFT_PANE_EXPAND = 3
CENTER_PANE_EXPAND = 5
RIGHT_PANE_EXPAND = 4
